_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.2
            "5": 0.19.9
            "8":
                - 1
                - 2
                - 5
            "12": 0.19.9
            "13": linux-x86_64
activation:
    value: relu
batch_norm:
    value: true
batch_size:
    value: 32
data_augmentation:
    value: true
data_root:
    value: ../inaturalist_data/nature_12K_extracted/inaturalist_12K
dropout_rate:
    value: 0.2
epochs:
    value: 2
filter_organization:
    value: same
learning_rate:
    value: 0.001
num_filters:
    value: 32
