part_a_configs:
  solution_1_configs:
    data_zip_path: "inaturalist_data/nature_12K.zip"
    extracted_data_dir: "inaturalist_data/nature_12K_extracted"

  solution_2_configs:
    data_root: "inaturalist_data/nature_12K_extracted/inaturalist_12K"
    gpu_count: 4
    wandb_project: "DA6401_Intro_to_DeepLearning_Assignment_2"
    wandb_entity: "Kaushik"
    wandb_run_tag: "Solution_2"
    sweep_count: 75
    correlation_run_name: "correlation_table_builder"

  solution_4_configs:
    data_root: "inaturalist_data/nature_12K_extracted/inaturalist_12K"
    wandb_project: 'trial' # "DA6401_Intro_to_DeepLearning_Assignment_2"
    wandb_run_name: "PartA_Q4_Solution_Best"
    output_dir: "outputs"
    patience: 3
    perform_early_stopping: True

part_b_configs:
  solution_3_configs:
    data_root: "inaturalist_data/nature_12K_extracted/inaturalist_12K"
    wandb_project: "test" # "DA6401_Intro_to_DeepLearning_Assignment_2"
    wandb_run_name: "PartB_Q3_Solution_Pretrained"
    model_configs:
      resize_dim: 352
      batch_size: 64
      
