# sweep_config.yaml
method: bayes  # or bayes / grid / random
metric:
  name: val_accuracy
  goal: maximize
parameters:
  num_filters:
    values: [16, 32, 64]
  kernel_size:
    values: [3, 5]
  activation_fn:
    values: ["relu", "gelu", "silu", "mish"]
  dense_neurons:
    values: [64, 128, 256]
  filter_organization:
    values: ["same", "double_each_layer", "halve_each_layer"]
  data_augmentation:
    values: [true, false]
  batch_norm:
    values: [true, false]
  dropout_rate:
    values: [0.2, 0.3, 0.0]  # 0 means no dropout
  learning_rate:
    values: [1e-3, 5e-4, 1e-4]
  batch_size:
    values: [8, 32, 64]
  epochs:
    values: [5, 10, 15, 20]
  resize_dim:
    values: [224, 352, 448]
