# sweep_config.yaml
method: random  # or bayes / grid
metric:
  name: val_accuracy
  goal: maximize
parameters:
  num_filters:
    values: [16, 32, 64]   # or [32, 64, 128]
  activation:
    values: ["relu", "gelu", "silu", "mish"]
  filter_organization:
    values: ["same", "double_each_layer", "halve_each_layer"]
  data_augmentation:
    values: [true, false]
  batch_norm:
    values: [true, false]
  dropout_rate:
    values: [0.2, 0.3, 0.0]  # 0 means no dropout
  learning_rate:
    values: [1e-3, 5e-4, 1e-4]
  batch_size:
    values: [32, 64]
